name: Build

on:
  schedule:
    - cron: "31 8 * * *"
  push:

jobs:
  build-latest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DATABASE: postgres
        ports:
            - 5432:5432
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.7'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Build
        env:
          PGPASSWORD: postgres
        run: |
          env
          PGPASSWORD=postgres psql --host localhost --port 5432 --username postgres --dbname postgres --list
